name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: AIzaSyChzc3yuz5ierUFG2P5gJrdAdVHj4ewOBk
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: math-kids-c984d.firebaseapp.com
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: math-kids-c984d
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: math-kids-c984d.firebasestorage.app
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "766062360362"
          NEXT_PUBLIC_FIREBASE_APP_ID: "1:766062360362:web:9de31d24869d543616d053"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
